// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc6504.MyRobot;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.AnalogGyro;
import edu.wpi.first.wpilibj.Compressor;
import edu.wpi.first.wpilibj.DoubleSolenoid;
import edu.wpi.first.wpilibj.PWMVictorSPX;
import edu.wpi.first.wpilibj.Spark;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.drive.MecanumDrive;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.livewindow.LiveWindow;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static SpeedController driveTrainFrontLeft;
    public static SpeedController driveTrainBackLeft;
    public static SpeedController driveTrainFrontRight;
    public static SpeedController driveTrainBackRight;
    public static MecanumDrive driveTrainRobotDrive;
    public static AnalogGyro driveTrainMyGyro;
    public static Compressor pneumaticsSubsystemCompressor1;
    public static DoubleSolenoid pneumaticsSubsystemDoubleSolenoid1;
    public static SpeedController liftStage1SubsystemSpeedController1;
    public static SpeedController liftStage2SubsystemSpeedController1;
    public static SpeedController intakeSubsystemSpeedController1;
    public static SpeedController intakeSubsystemSpeedController2;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        driveTrainFrontLeft = new Spark(1);
        LiveWindow.addActuator("DriveTrain", "Front Left", (Spark) driveTrainFrontLeft);
        driveTrainFrontLeft.setInverted(false);
        driveTrainBackLeft = new Spark(2);
        LiveWindow.addActuator("DriveTrain", "Back Left ", (Spark) driveTrainBackLeft);
        driveTrainBackLeft.setInverted(false);
        driveTrainFrontRight = new Spark(3);
        LiveWindow.addActuator("DriveTrain", "Front Right", (Spark) driveTrainFrontRight);
        driveTrainFrontRight.setInverted(false);
        driveTrainBackRight = new Spark(4);
        LiveWindow.addActuator("DriveTrain", "Back Right", (Spark) driveTrainBackRight);
        driveTrainBackRight.setInverted(false);
        driveTrainRobotDrive = new MecanumDrive(driveTrainFrontLeft, driveTrainBackLeft,
              driveTrainFrontRight, driveTrainBackRight);
        LiveWindow.addActuator("DriveTrain", "Robot Drive", driveTrainRobotDrive);
        driveTrainRobotDrive.setSafetyEnabled(true);
        driveTrainRobotDrive.setExpiration(0.1);
        driveTrainRobotDrive.setMaxOutput(1.0);

        driveTrainMyGyro = new AnalogGyro(0);
        LiveWindow.addSensor("DriveTrain", "MyGyro", driveTrainMyGyro);
        driveTrainMyGyro.setSensitivity(0.007);
        pneumaticsSubsystemCompressor1 = new Compressor(0);
        LiveWindow.addActuator("PneumaticsSubsystem", "Compressor 1", pneumaticsSubsystemCompressor1);
        
        pneumaticsSubsystemDoubleSolenoid1 = new DoubleSolenoid(0, 5, 4);
        LiveWindow.addActuator("PneumaticsSubsystem", "Double Solenoid 1", pneumaticsSubsystemDoubleSolenoid1);
        
        liftStage1SubsystemSpeedController1 = new PWMVictorSPX(0);
        LiveWindow.addActuator("LiftStage1Subsystem", "Speed Controller 1", (PWMVictorSPX) liftStage1SubsystemSpeedController1);
        liftStage1SubsystemSpeedController1.setInverted(false);
        liftStage2SubsystemSpeedController1 = new PWMVictorSPX(5);
        LiveWindow.addActuator("LiftStage2Subsystem", "Speed Controller 1", (PWMVictorSPX) liftStage2SubsystemSpeedController1);
        liftStage2SubsystemSpeedController1.setInverted(false);
        intakeSubsystemSpeedController1 = new Spark(6);
        LiveWindow.addActuator("IntakeSubsystem", "Speed Controller 1", (Spark) intakeSubsystemSpeedController1);
        intakeSubsystemSpeedController1.setInverted(false);
        intakeSubsystemSpeedController2 = new Spark(7);
        LiveWindow.addActuator("IntakeSubsystem", "Speed Controller 2", (Spark) intakeSubsystemSpeedController2);
        intakeSubsystemSpeedController2.setInverted(false);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
